server:
  port: 8087

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: false

      routes:
        - id: product-catalog-service
          uri: lb://product-catalog-service
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<path>.*), /$\{path}
        - id: shopping-cart-service
          uri: lb://shopping-cart-service
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/cart/(?<path>.*), /$\{path}
        - id: logbook-service
          uri: lb://logbook-service
          predicates:
            - Path=/log/**
          filters:
            - RewritePath=/log/(?<path>.*), /$\{path}



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
